framework:
    secret: '%env(APP_SECRET)%'
    translator: { fallbacks: ['%env(LOCALE)%'] }
    csrf_protection: true
    http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_samesite: lax
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_lifetime: 86400  #time in seconds
        gc_maxlifetime: 86400
        cookie_httponly: false
        cookie_path: "%session_cookie_path%"
    #esi: true
    fragments: true
    php_errors:
        log: true
    templating:
        engines: ['twig']
    default_locale: '%env(LOCALE)%'
    trusted_hosts: ~
    php_errors:
        log: true

