# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    role_hierarchy:
        ROLE_OWNER:         ROLE_USER
        ROLE_ADMIN:         ROLE_OWNER
        ROLE_SUPER_ADMIN:   ROLE_ADMIN

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            form_login:
                provider: app_user_provider
                login_path: login
                check_path: login
                enable_csrf: true
            logout:
                path: app_logout

    access_control:
        - { path: ^/register, role: ROLE_SUPER_ADMIN }
        - { path: ^/login$, role: PUBLIC_ACCESS }
        - { path: ^/$, role: PUBLIC_ACCESS }
        - { path: ^/trigger/, role: PUBLIC_ACCESS }
        - { path: ^/stat/, role: PUBLIC_ACCESS }
        - { path: ^/rpc/, role: PUBLIC_ACCESS }
        - { path: ^/solar_api/, role: PUBLIC_ACCESS }
        - { path: ^/resetting, role: PUBLIC_ACCESS }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }
