twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        locale: '%locale%'
        connectors: '%connectors%'
        instancetitle: '%instancetitle%'
        smartfoxConnector: '@App\Utils\Connectors\SmartFoxConnector'
        chromecastConnector: '@App\Utils\Connectors\ChromecastConnector'
        mobilealertsConnector: '@App\Utils\Connectors\MobileAlertsConnector'
        mystromConnector: '@App\Utils\Connectors\MyStromConnector'
        shellyConnector: '@App\Utils\Connectors\ShellyConnector'
        pcowebConnector: '@App\Utils\Connectors\PcoWebConnector'
        ecarConnector: '@App\Utils\Connectors\EcarConnector'
        gardenaConnector: '@App\Utils\Connectors\GardenaConnector'
        netatmoConnector: '@App\Utils\Connectors\NetatmoConnector'
        conditionChecker: '@App\Utils\ConditionChecker'
    file_name_pattern: '*.twig'

when@test:
    twig:
        strict_variables: true