services:
  www:
    image: oshans/www_${INSTANCENAME}:0.0.1
    container_name: clevergy_www_${INSTANCENAME}
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - type: bind
        source: ./www/config/parameters.yaml
        target: /www/config/parameters.yaml
      - ./www/var/sessions:/www/var/sessions
      - ${BACKUP_DIR}:/backup
    env_file:
      - ./www/.env.local
    environment:
      - TZ=${TZ}
      - servername=${HOSTNAME}
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
          INSTANCENAME: ${INSTANCENAME}
          BACKUP_HOUR: ${BACKUP_HOUR}
    networks:
      - default
    ports:
      - "${PORT}:443"
    depends_on:
      - db
      - python
    restart: always

  python:
    image: oshans/py_${INSTANCENAME}:0.0.1
    container_name: clevergy_py_${INSTANCENAME}
    stdin_open: true
    tty: true
    volumes:
      - ./python:/python
    build:
      context: ./
      dockerfile: ./python/Dockerfile
    networks:
      - default
    ports:
      - "8192:8192"
    restart: always

  db:
    image: mysql/mysql-server:8.0
    container_name: clevergy_db_${INSTANCENAME}
    command:
      - --default-authentication-plugin=mysql_native_password
      - --sort_buffer_size=1073741824
      - --disable-log-bin
    volumes:
      - ./data/db:/var/lib/mysql
      - ${BACKUP_DIR}:/backup
    environment:
      - TZ=Europe/Zurich
    env_file:
      - ./db.env
    networks:
      - default
    restart: always
#    ports:
#      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    container_name: clevergy_phpmyadmin_${INSTANCENAME}
    environment:
      - TZ=Europe/Zurich
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
      - PMA_ABSOLUTE_URI=http://localhost
    networks:
      - default
    links:
      - db
    restart: always
#    ports:
#      - "8080:80"
