version: '3.7'

services:
  www:
    image: oshans/www_${INSTANCENAME}:0.0.1
    container_name: www_${INSTANCENAME}
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - type: bind
        source: ./config/parameters.yaml
        target: /www/config/parameters.yaml
      - ./var/sessions:/www/var/sessions
    env_file:
      - ./.env.local
    environment:
      - TZ=Europe/Zurich
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - default
    ports:
      - "${PORT}:8000"
    restart: always
